// Generated by scripts/build-motion-cache.mjs. Do not edit by hand.
export const MOTION_ASSETS:Record<string,{revision:string;bytes:number}>={
 "/effects/royal-table/courtyard.webp": {
  "revision": "cb91f999236824e2605e",
  "bytes": 102720
 },
 "/effects/royal-table/king/enter.webp": {
  "revision": "98de2afe243e8d092e4f",
  "bytes": 81314
 },
 "/effects/royal-table/king/idle.webp": {
  "revision": "8e0a3168007e8c7aa31b",
  "bytes": 71926
 },
 "/effects/royal-table/king/lose.webp": {
  "revision": "158f07bf0a4133ae11f3",
  "bytes": 73784
 },
 "/effects/royal-table/king/pass.webp": {
  "revision": "452da0120b4adba23a84",
  "bytes": 81258
 },
 "/effects/royal-table/king/play.webp": {
  "revision": "9f401858e833f183fe71",
  "bytes": 82228
 },
 "/effects/royal-table/king/poster.webp": {
  "revision": "868f6babcfdb44030e72",
  "bytes": 18904
 },
 "/effects/royal-table/king/win.webp": {
  "revision": "500df3dbeb21e1a215cf",
  "bytes": 86224
 },
 "/effects/royal-table/princess/enter.webp": {
  "revision": "15cd08e40d42234cc153",
  "bytes": 82570
 },
 "/effects/royal-table/princess/idle.webp": {
  "revision": "70270f06993d4345ae9a",
  "bytes": 73298
 },
 "/effects/royal-table/princess/lose.webp": {
  "revision": "32b8a3023ad7916d1043",
  "bytes": 75404
 },
 "/effects/royal-table/princess/pass.webp": {
  "revision": "40983ca618befdeee404",
  "bytes": 82922
 },
 "/effects/royal-table/princess/play.webp": {
  "revision": "a92f2c0ea54b4f086e80",
  "bytes": 87082
 },
 "/effects/royal-table/princess/poster.webp": {
  "revision": "fa787d5504420d7a94c7",
  "bytes": 19592
 },
 "/effects/royal-table/princess/win.webp": {
  "revision": "5f02db78346973fa548f",
  "bytes": 92120
 },
 "/effects/v1/airplane-pair/atlas.webp": {
  "revision": "e7a409bcb4bc0dd27548",
  "bytes": 744674
 },
 "/effects/v1/airplane-pair/poster.webp": {
  "revision": "fe238c209ebc448a6bd8",
  "bytes": 43654
 },
 "/effects/v1/airplane-single/atlas.webp": {
  "revision": "3e89e3b52c00f10c7158",
  "bytes": 709272
 },
 "/effects/v1/airplane-single/poster.webp": {
  "revision": "6933b37e6353115170a3",
  "bytes": 41886
 },
 "/effects/v1/airplane/atlas.webp": {
  "revision": "133d350a22bc0876ee8f",
  "bytes": 629328
 },
 "/effects/v1/airplane/poster.webp": {
  "revision": "888e8e1431076cf57e29",
  "bytes": 38900
 },
 "/effects/v1/anti-spring/poster.webp": {
  "revision": "01fc0743c8a9467d4a40",
  "bytes": 63606
 },
 "/effects/v1/bomb/atlas.webp": {
  "revision": "07a3fdc4f48538c4ce52",
  "bytes": 493344
 },
 "/effects/v1/bomb/poster.webp": {
  "revision": "3ea602b2a99635e9aae5",
  "bytes": 25018
 },
 "/effects/v1/chi/poster.webp": {
  "revision": "985a4b80f499e2505c65",
  "bytes": 52004
 },
 "/effects/v1/four-pairs/poster.webp": {
  "revision": "adc22e02884742d53d0d",
  "bytes": 45038
 },
 "/effects/v1/four-two/poster.webp": {
  "revision": "d77abc488804243b2f8c",
  "bytes": 52344
 },
 "/effects/v1/hu/atlas.webp": {
  "revision": "6575738da99cac372b01",
  "bytes": 671678
 },
 "/effects/v1/hu/poster.webp": {
  "revision": "1f6da37c36222691eeeb",
  "bytes": 32618
 },
 "/effects/v1/kong/poster.webp": {
  "revision": "60b38a6e611446ea2521",
  "bytes": 45538
 },
 "/effects/v1/pairs/poster.webp": {
  "revision": "75e61f2e91f180d5c52f",
  "bytes": 56526
 },
 "/effects/v1/pong/poster.webp": {
  "revision": "e3c83ffaaa45f6db52c5",
  "bytes": 57190
 },
 "/effects/v1/rocket/atlas.webp": {
  "revision": "f4705d2f908c0d37f99a",
  "bytes": 688700
 },
 "/effects/v1/rocket/poster.webp": {
  "revision": "9ce82e79ac832c93a9d0",
  "bytes": 40798
 },
 "/effects/v1/spring/poster.webp": {
  "revision": "046546653303820bedbf",
  "bytes": 58586
 },
 "/effects/v1/straight/poster.webp": {
  "revision": "c59402c28e8cd7a278b1",
  "bytes": 51772
 },
 "/emotes/royale-v1/angry.webp": {
  "revision": "f7ac65e592a21e9da2ed",
  "bytes": 27692
 },
 "/emotes/royale-v1/celebrate.webp": {
  "revision": "ae12da562a7ca0f9e037",
  "bytes": 33436
 },
 "/emotes/royale-v1/clap.webp": {
  "revision": "d9c3b9b71cd4f83571b2",
  "bytes": 35686
 },
 "/emotes/royale-v1/cry.webp": {
  "revision": "75fc1340143b509be8eb",
  "bytes": 24058
 },
 "/emotes/royale-v1/hello.webp": {
  "revision": "fdd438a773630814fac2",
  "bytes": 31536
 },
 "/emotes/royale-v1/laugh.webp": {
  "revision": "4a0bd3c357f78974caea",
  "bytes": 21670
 },
 "/emotes/royale-v1/like.webp": {
  "revision": "32a0f208af1154c60505",
  "bytes": 30292
 },
 "/emotes/royale-v1/salute.webp": {
  "revision": "7714b64d3a12b2049b30",
  "bytes": 26994
 },
 "/emotes/royale-v1/shocked.webp": {
  "revision": "be2265d671b1e8ac8b75",
  "bytes": 30264
 },
 "/emotes/royale-v1/sigh.webp": {
  "revision": "f7b254c0fdd3937d3de4",
  "bytes": 35358
 },
 "/emotes/royale-v1/smug.webp": {
  "revision": "630f503e6f730c411988",
  "bytes": 27976
 },
 "/emotes/royale-v1/think.webp": {
  "revision": "1c7ba61f2a39e7490b64",
  "bytes": 29598
 },
 "/emotes/royale-v2/barbarian-laugh/atlas.webp": {
  "revision": "530794f4de7b959b6732",
  "bytes": 479054
 },
 "/emotes/royale-v2/barbarian-laugh/poster.webp": {
  "revision": "c8b432e27c6d36d99811",
  "bytes": 17584
 },
 "/emotes/royale-v2/chicken/atlas.webp": {
  "revision": "ffe14bc565552202bd1b",
  "bytes": 335770
 },
 "/emotes/royale-v2/chicken/poster.webp": {
  "revision": "69a28825d2180bd3db24",
  "bytes": 13526
 },
 "/emotes/royale-v2/electro-laugh/atlas.webp": {
  "revision": "712b9851296d24d7437c",
  "bytes": 544854
 },
 "/emotes/royale-v2/electro-laugh/poster.webp": {
  "revision": "c4e3a456370ae7289ca2",
  "bytes": 23172
 },
 "/emotes/royale-v2/goblin-cry/atlas.webp": {
  "revision": "14170d963afd53c9ce6c",
  "bytes": 465302
 },
 "/emotes/royale-v2/goblin-cry/poster.webp": {
  "revision": "fd5984a997d7d55abdb3",
  "bytes": 17456
 },
 "/emotes/royale-v2/goblin-eye-roll/atlas.webp": {
  "revision": "e58b8ca9abfacf9ed32f",
  "bytes": 389272
 },
 "/emotes/royale-v2/goblin-eye-roll/poster.webp": {
  "revision": "6ae9a5427872e1dc1dac",
  "bytes": 16930
 },
 "/emotes/royale-v2/goblin-facepalm/atlas.webp": {
  "revision": "59cd7522f427f0c345dc",
  "bytes": 363168
 },
 "/emotes/royale-v2/goblin-facepalm/poster.webp": {
  "revision": "1e205db180a381fd4506",
  "bytes": 14930
 },
 "/emotes/royale-v2/goblin-fire/atlas.webp": {
  "revision": "c2eb0fc2db3c8983cf7e",
  "bytes": 407226
 },
 "/emotes/royale-v2/goblin-fire/poster.webp": {
  "revision": "cbaf8fa21a1954b6d7b2",
  "bytes": 18364
 },
 "/emotes/royale-v2/goblin-laugh/atlas.webp": {
  "revision": "58a82767c9d1350394a5",
  "bytes": 410466
 },
 "/emotes/royale-v2/goblin-laugh/poster.webp": {
  "revision": "19f91245f21bc8ea7154",
  "bytes": 16896
 },
 "/emotes/royale-v2/goblin-tongue/atlas.webp": {
  "revision": "0efac09670db53660f8a",
  "bytes": 348288
 },
 "/emotes/royale-v2/goblin-tongue/poster.webp": {
  "revision": "0a2b741e731aca3a9d35",
  "bytes": 14670
 },
 "/emotes/royale-v2/hog-scream/atlas.webp": {
  "revision": "2828a5ce0efd1fa03741",
  "bytes": 488732
 },
 "/emotes/royale-v2/hog-scream/poster.webp": {
  "revision": "c91463992d2066de40f9",
  "bytes": 19810
 },
 "/emotes/royale-v2/hog-think/atlas.webp": {
  "revision": "da0f740fb947b57bd732",
  "bytes": 415848
 },
 "/emotes/royale-v2/hog-think/poster.webp": {
  "revision": "12b464b6b81d280ae9fc",
  "bytes": 16582
 },
 "/emotes/royale-v2/king-angry/atlas.webp": {
  "revision": "c47baf8bf2717415f084",
  "bytes": 480118
 },
 "/emotes/royale-v2/king-angry/poster.webp": {
  "revision": "e5af4d0a17d011558727",
  "bytes": 21480
 },
 "/emotes/royale-v2/king-cry/atlas.webp": {
  "revision": "aa4c0f22acef29bbade3",
  "bytes": 348994
 },
 "/emotes/royale-v2/king-cry/poster.webp": {
  "revision": "ff9fe7ab6288cf6f242c",
  "bytes": 15106
 },
 "/emotes/royale-v2/king-laugh/atlas.webp": {
  "revision": "c40fd6f23783f6c2514d",
  "bytes": 339804
 },
 "/emotes/royale-v2/king-laugh/poster.webp": {
  "revision": "e931612622e0076c9815",
  "bytes": 14948
 },
 "/emotes/royale-v2/king-thumbs-up/atlas.webp": {
  "revision": "3340854baa05810d8426",
  "bytes": 412728
 },
 "/emotes/royale-v2/king-thumbs-up/poster.webp": {
  "revision": "5207dc53e771aee6df05",
  "bytes": 18268
 },
 "/emotes/royale-v2/little-prince-cry/atlas.webp": {
  "revision": "0a60e1da473cc033bc02",
  "bytes": 461284
 },
 "/emotes/royale-v2/little-prince-cry/poster.webp": {
  "revision": "0f256b3a20265e2433ee",
  "bytes": 17804
 },
 "/emotes/royale-v2/pig-twerk/atlas.webp": {
  "revision": "ce3fbb866d1308347ae3",
  "bytes": 369048
 },
 "/emotes/royale-v2/pig-twerk/poster.webp": {
  "revision": "b306b0addf423a430ca8",
  "bytes": 17566
 },
 "/emotes/royale-v2/princess-whistle/atlas.webp": {
  "revision": "9b7e4282be577112e249",
  "bytes": 374206
 },
 "/emotes/royale-v2/princess-whistle/poster.webp": {
  "revision": "629c88c4a26819ca140f",
  "bytes": 14736
 },
 "/emotes/royale-v2/princess-yawn/atlas.webp": {
  "revision": "71814684bc02423e145b",
  "bytes": 424606
 },
 "/emotes/royale-v2/princess-yawn/poster.webp": {
  "revision": "29f0c51842bdcfb00472",
  "bytes": 17620
 },
 "/emotes/royale-v2/skeleton-cry/atlas.webp": {
  "revision": "c6e3f40fc77448f2e7cc",
  "bytes": 344612
 },
 "/emotes/royale-v2/skeleton-cry/poster.webp": {
  "revision": "b96523f21d6ae8d6edd2",
  "bytes": 14294
 },
 "/emotes/royale-v2/skeleton-dance/atlas.webp": {
  "revision": "467c18c3642c5e9164a6",
  "bytes": 432058
 },
 "/emotes/royale-v2/skeleton-dance/poster.webp": {
  "revision": "c352db6599cf63ff8871",
  "bytes": 21598
 }
};
