"use client";
import { useState } from "react";
import { ArrowRight, Club, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function AuthScreen({onAuth,setup=false,token=""}:{onAuth:(user:any)=>void;setup?:boolean;token?:string}) {
  const [mode,setMode]=useState(setup?"setup":"login");
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:mode,username:f.get("username"),password:f.get("password"),name:f.get("name"),token})});const d:any=await r.json();if(!r.ok)throw Error(d.error);onAuth(d.user)}catch(e){setError((e as Error).message||"连接失败，请重试")}finally{setBusy(false)}}
  return <main className="entry auth-cartoon"><header className="brand"><span className="brand-icon"><Club size={24}/></span><span>娱乐中心<small>好 友 游 戏 室</small></span></header><section className="entry-table" aria-hidden="true"><div className="table-center"><Sparkles className="auth-sparkle" size={38}/><h1>来一局？</h1><div className="display-hand"><div className="playing-card black rotate-left"><b>A</b><span>♠</span><i>♠</i></div><div className="playing-card red"><b>A</b><span>♥</span><i>♥</i></div><div className="playing-card black rotate-right"><b>A</b><span>♣</span><i>♣</i></div></div></div></section><section className="login-panel"><div className="login-inner"><h2>{setup?"设置管理员账号":"欢迎来玩"}</h2>{!setup&&<Tabs value={mode} onValueChange={setMode}><TabsList className="auth-tabs"><TabsTrigger value="login" disabled={busy}>登录</TabsTrigger><TabsTrigger value="register" disabled={busy}>注册</TabsTrigger></TabsList></Tabs>}<form onSubmit={submit}><label htmlFor="username">用户名</label><Input name="username" minLength={3} maxLength={24} defaultValue={setup?"MartinHamburger":""} readOnly={setup} id="username" placeholder="你的用户名" autoComplete="username" required/><label htmlFor="password">密码</label><Input name="password" minLength={10} maxLength={128} id="password" type="password" placeholder={mode==="login"?"你的密码":"至少 10 个字符"} autoComplete={mode==="login"?"current-password":"new-password"} required/>{mode==="register"&&<><label htmlFor="nickname">昵称（选填）</label><Input id="nickname" name="name" maxLength={16} placeholder="朋友怎么称呼你"/></>}{error&&<p role="alert" className="form-error">{error}</p>}<Button disabled={busy} type="submit" className="primary-button">{busy?"请稍等…":mode==="login"?"登录":setup?"保存并进入后台":"注册"}<ArrowRight size={18}/></Button></form></div></section></main>
}
