"use client";
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {ImagePlus,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './ui/dialog';
import {Button} from './ui/button';
import {cropRect,inspectImage,MAX_AVATAR_BYTES} from '@/lib/avatar/image';
import type {AvatarProfile} from '@/lib/avatar/profile';
type Draft={bitmap:ImageBitmap;url:string;zoom:number;x:number;y:number};
export function AvatarEditor({userId,profile,accept,close}:{userId:string;profile:AvatarProfile;accept:(p:AvatarProfile[])=>void;close:()=>void}){
 const [draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[version,setVersion]=useState(profile.version),[preview,setPreview]=useState(profile.url);
 const input=useRef<HTMLInputElement>(null),current=useRef<Draft|null>(null),serial=useRef(0),controller=useRef<AbortController|null>(null),alive=useRef(true),drag=useRef<{id:number;x:number;y:number;startX:number;startY:number;width:number}|null>(null);current.current=draft;
 const updateProfile=(p:AvatarProfile)=>{if(p.id!==userId)return;accept([p]);setVersion(p.version);setPreview(p.url)};
 useEffect(()=>{const c=new AbortController();controller.current=c;alive.current=true;void fetch('/api/profile/avatar',{signal:AbortSignal.any([c.signal,AbortSignal.timeout(12000)]),cache:'no-store'}).then(async r=>{const p=await r.json() as AvatarProfile&{error?:string};if(!r.ok)throw Error(p.error||'头像资料无法读取');if(alive.current)updateProfile(p)}).catch(()=>{if(alive.current)setError('头像资料暂时连接不上，请关闭后重试')}).finally(()=>{if(alive.current)setLoading(false)});return()=>{alive.current=false;serial.current++;controller.current?.abort();current.current?.bitmap.close();if(current.current)URL.revokeObjectURL(current.current.url)}},[userId]);
 async function choose(file?:File){if(!file)return;const ticket=++serial.current;setError('');setLoading(true);let bitmap:ImageBitmap|null=null;try{
  if(file.size>10*1024*1024)throw Error('原图不能超过 10MB');inspectImage(new Uint8Array(await file.arrayBuffer()));bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});if(bitmap.width*bitmap.height>24_000_000)throw Error('图片不得超过 2400 万像素');if(!alive.current||ticket!==serial.current){bitmap.close();return;}
  current.current?.bitmap.close();if(current.current)URL.revokeObjectURL(current.current.url);setDraft({bitmap,url:URL.createObjectURL(file),zoom:1,x:.5,y:.5});
 }catch(e){bitmap?.close();if(alive.current&&ticket===serial.current)setError((e as Error).message||'图片无法读取，请更换图片')}
 finally{if(alive.current&&ticket===serial.current)setLoading(false);if(input.current)input.current.value='';}}
 function move(e:PointerEvent<HTMLDivElement>){const d=drag.current;if(!draft||!d||d.id!==e.pointerId)return;const rect=cropRect(draft.bitmap.width,draft.bitmap.height,draft.zoom,draft.x,draft.y),scale=d.width/rect.size;const next=cropRect(draft.bitmap.width,draft.bitmap.height,draft.zoom,d.startX-(e.clientX-d.x)/scale/draft.bitmap.width,d.startY-(e.clientY-d.y)/scale/draft.bitmap.height);setDraft({...draft,x:next.x,y:next.y});}
 async function save(remove=false){if(busy||loading||(!remove&&!draft))return;setBusy(true);setError('');const c=new AbortController();controller.current=c;
  try{let blob:Blob|undefined;if(!remove&&draft){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');if(!ctx)throw Error('浏览器暂不支持图片裁剪');ctx.fillStyle='#f7f4e9';ctx.fillRect(0,0,256,256);const r=cropRect(draft.bitmap.width,draft.bitmap.height,draft.zoom,draft.x,draft.y);ctx.drawImage(draft.bitmap,r.left,r.top,r.size,r.size,0,0,256,256);for(const quality of [.9,.8,.65,.5]){blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('图片转换失败，请重试')),'image/jpeg',quality));if(blob.size<=MAX_AVATAR_BYTES)break;}if(!blob||blob.size>MAX_AVATAR_BYTES)throw Error('图片压缩失败，请更换图片');}
   const response=await fetch('/api/profile/avatar',{method:remove?'DELETE':'PUT',headers:{'If-Match':String(version),...(!remove?{'Content-Type':'image/jpeg'}:{})},body:blob,signal:AbortSignal.any([c.signal,AbortSignal.timeout(12000)])});const result=await response.json() as AvatarProfile&{error?:string;profile?:AvatarProfile};if(!alive.current)return;if(result.profile)updateProfile(result.profile);if(!response.ok)throw Error(result.error||'头像保存失败，请重试');updateProfile(result);close();
  }catch(e){if(alive.current){setError((e as Error).name==='TimeoutError'||(e as Error).name==='AbortError'?'保存超时，正在核实当前头像；裁剪已保留，请核实后手动重试':(e as Error).message);try{const r=await fetch('/api/profile/avatar',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(r.ok&&alive.current)updateProfile(await r.json())}catch{}}}
  finally{if(alive.current)setBusy(false);}
 }
 const r=draft?cropRect(draft.bitmap.width,draft.bitmap.height,draft.zoom,draft.x,draft.y):null;
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)close()}}><DialogContent className="avatar-editor" showCloseButton={!busy}><DialogHeader><DialogTitle>更换头像</DialogTitle><DialogDescription>选择静态 JPG、PNG 或 WebP，拖动照片并缩放取景。原图不超过 10MB、2400 万像素。</DialogDescription></DialogHeader>
 <input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden aria-label="选择头像图片" onChange={e=>void choose(e.target.files?.[0])}/>
 <div className={`avatar-crop ${draft?'has-photo':''}`} aria-label="头像裁剪预览" onPointerDown={e=>{if(!draft||busy)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,startX:draft.x,startY:draft.y,width:e.currentTarget.clientWidth}}} onPointerMove={move} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}>
 {draft&&r?<img draggable={false} src={draft.url} alt="待裁剪的头像" style={{width:`${draft.bitmap.width/r.size*100}%`,height:`${draft.bitmap.height/r.size*100}%`,left:`${-r.left/r.size*100}%`,top:`${-r.top/r.size*100}%`}}/>:preview?<img src={preview} alt="当前头像"/>:<ImagePlus aria-hidden size={56}/>}
 {draft&&<span className="avatar-crop-grid" aria-hidden/>}</div>
 <Button variant="outline" onClick={()=>input.current?.click()} disabled={busy||loading}><ImagePlus size={16}/>{draft?'更换图片':'选择图片'}</Button>
 {draft&&<><label className="avatar-zoom">缩放<input aria-label="头像缩放" type="range" min="1" max="3" step=".01" value={draft.zoom} disabled={busy} onChange={e=>{const zoom=Number(e.target.value),r=cropRect(draft.bitmap.width,draft.bitmap.height,zoom,draft.x,draft.y);setDraft({...draft,zoom,x:r.x,y:r.y})}}/><span>{Math.round(draft.zoom*100)}%</span></label><div className="avatar-nudge" aria-label="调整裁剪位置">{[['向左',-.04,0],['向上',0,-.04],['居中',0,0],['向下',0,.04],['向右',.04,0]].map(([name,x,y])=><button key={name} type="button" disabled={busy} onClick={()=>{const r=cropRect(draft.bitmap.width,draft.bitmap.height,draft.zoom,name==='居中'?.5:draft.x+Number(x),name==='居中'?.5:draft.y+Number(y));setDraft({...draft,x:r.x,y:r.y})}}>{name}</button>)}</div></>}
 <p className="avatar-help">只保存裁剪后的头像，不保留原图。保存后可随时更换或恢复默认。</p>{loading&&<p role="status">正在读取图片或资料…</p>}{error&&<p className="avatar-error" role="alert">{error}</p>}
 <div className="avatar-editor-actions"><Button variant="ghost" disabled={busy||loading||!preview} onClick={()=>void save(true)}><RotateCcw size={14}/>恢复默认</Button><Button variant="outline" disabled={busy} onClick={close}>取消</Button><Button disabled={busy||loading||!draft} onClick={()=>void save()}>{busy?'保存中…':'保存头像'}</Button></div>
 </DialogContent></Dialog>;
}
