"use client";
import {PlayerAvatar} from './player-avatar';
import {useState} from 'react';
import {Check,Mail,UserPlus,Users} from 'lucide-react';
import {useFriends} from './friends-provider';
import {useClub,useRoomNavigation} from './club-provider';
import {roomInviteProblem,type SocialPerson} from '@/lib/club/social';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from './ui/dialog';
const gameNames={landlord:'斗地主','landlord-v3':'斗地主',mahjong:'麻将',holdem:'德州扑克'};
function Person({person,online}:{person:SocialPerson;online?:boolean}){return <div className="friend-person"><span className="friend-avatar"><PlayerAvatar name={person.name} userId={person.id}/>{online!==undefined&&<i className={online?'is-online':''}/>}</span><div><b>{person.name}</b>{online!==undefined&&<small>{online?'在线':'离线'}</small>}</div></div>}
export function FriendsPanel({all=false,roomCode,inviteDisabled=false,onJoined}:{all?:boolean;roomCode?:string;inviteDisabled?:boolean;onJoined?:()=>void}){
 const {data,ready,busy,error,send,refresh}=useFriends(),{lobby}=useClub(),{openRoom}=useRoomNavigation();
 const [notice,setNotice]=useState(''),[failure,setFailure]=useState(''),[joining,setJoining]=useState(false),[sent,setSent]=useState<string[]>([]);
 const code=roomCode??lobby?.activeRoom??undefined,online=data.friends.filter(f=>f.online),people=all?data.friends:online,disabled=busy||joining;
 async function act(payload:Record<string,unknown>,success:string){setFailure('');setNotice('');try{await send(payload);setNotice(success);if(payload.action==='invite')setSent(s=>[...s,`${payload.code}:${payload.target}`]);}catch(e){setFailure((e as Error).message)}}
 async function join(inviteId:string){setJoining(true);setFailure('');setNotice('');try{const destination=await send({action:'open_invite',inviteId});await openRoom(destination.game,destination.code,true);onJoined?.();await send({action:'dismiss_invite',inviteId});setNotice('已加入好友的房间');}catch(e){setFailure((e as Error).message);void refresh();}finally{setJoining(false)}}
 return <section className="friends-panel" aria-label={all?'我的好友':'在线好友'}><div className="friends-heading"><h3><Users size={18}/>{all?'我的好友':'在线好友'} <span>{ready?online.length:'—'}</span></h3><button type="button" onClick={()=>void refresh()} disabled={disabled}>刷新</button></div>
 {failure&&<p role="alert" className="friends-error">{failure}</p>}{notice&&<p role="status" className="friends-notice">{notice}</p>}
 {error?<p role="status" className="friends-empty">{error}</p>:!ready?<p className="friends-empty">正在看看谁在线…</p>:<>
 {data.invites.length>0&&<section className="social-section"><h4>房间邀请 <span>{data.invites.length}</span></h4>{data.invites.map(i=><article className="friend-invite" key={i.id}><p><b>{i.from.name}</b> 邀请你来一桌</p><small>{gameNames[i.game]} · {i.title} · {i.code}</small><div className="social-actions"><Button size="sm" disabled={disabled} onClick={()=>void join(i.id)}>接受并入座</Button><Button size="sm" variant="ghost" disabled={disabled} onClick={()=>void act({action:'dismiss_invite',inviteId:i.id},'已忽略邀请')}>忽略</Button></div></article>)}</section>}
 {data.incoming.length>0&&<section className="social-section"><h4>好友申请 <span>{data.incoming.length}</span></h4>{data.incoming.map(p=><article className="friend-request" key={p.id}><Person person={p}/><div className="social-actions"><Button size="sm" disabled={disabled} aria-label={`同意 ${p.name} 的好友申请`} onClick={()=>void act({action:'accept',target:p.id},`你和 ${p.name} 已成为好友`)}>同意</Button><Button size="sm" variant="ghost" disabled={disabled} aria-label={`忽略 ${p.name} 的好友申请`} onClick={()=>void act({action:'decline',target:p.id},'已忽略申请')}>忽略</Button></div></article>)}</section>}
 <div className="friend-list">{people.map(p=>{const invited=sent.includes(`${code}:${p.id}`);return <div className="friend-row" key={p.id}><Person person={p} online={p.online}/><Button size="sm" variant="outline" aria-label={`邀请 ${p.name} 入座`} disabled={disabled||!code||inviteDisabled||invited} onClick={()=>void act({action:'invite',target:p.id,code},`已邀请 ${p.name}，等待对方入座`)}>{invited?'已邀请':'邀请入座'}</Button></div>})}</div>
 {!people.length&&<p className="friends-empty">{data.friends.length?'好友暂时都不在线，晚点再约一桌。':'还没有好友。在对局中打开「同桌好友」，认识下一位牌搭子。'}</p>}
 {!code&&people.length>0&&<p className="friends-hint">开一桌后，就能邀请好友入座。</p>}{!all&&data.friends.length>online.length&&<p className="friends-hint">另有 {data.friends.length-online.length} 位好友离线</p>}
 {data.outgoing.length>0&&<details className="social-outgoing"><summary>已发送的申请 · {data.outgoing.length}</summary>{data.outgoing.map(p=><div className="friend-row" key={p.id}><Person person={p}/><Button variant="ghost" size="sm" disabled={disabled} aria-label={`撤回给 ${p.name} 的申请`} onClick={()=>void act({action:'cancel',target:p.id},'已撤回申请')}>撤回</Button></div>)}</details>}
 </>}</section>;
}
export function FriendsMenu(){const [open,setOpen]=useState(false);const {data}=useFriends();const count=data.incoming.length+data.invites.length;return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="ghost" className="club-friends-link" aria-label={`好友${count?`，${count} 条待处理消息`:''}`}><Users size={17}/><span>好友</span>{count>0&&<b className="social-count">{count}</b>}</Button></DialogTrigger><DialogContent className="social-modal"><DialogHeader><DialogTitle>好友与邀请</DialogTitle><DialogDescription>同意申请后成为好友，接受房间邀请后才会入座。</DialogDescription></DialogHeader><FriendsPanel all onJoined={()=>setOpen(false)}/></DialogContent></Dialog>}
type TableGame={kind?:string;phase:string;seats:{id:string;name:string;bot?:boolean}[];fixed?:boolean;fixedIds?:string[];roundNumber?:number;rules?:{id?:string;capacity?:number}};
export function RoomFriends({code,game}:{code:string;game:TableGame}){
 const {user}=useClub(),{data,busy,ready,send,refresh}=useFriends(),[error,setError]=useState(''),[open,setOpen]=useState(false);
 const peers=game.seats.filter(p=>p.id!==user?.id&&!p.bot),problem=roomInviteProblem(game);
 async function add(p:SocialPerson){setError('');try{await send({action:'request',target:p.id,code});}catch(e){setError((e as Error).message)}}
 return <Dialog open={open} onOpenChange={open=>{setOpen(open);if(open)void refresh()}}><DialogTrigger asChild><Button variant="ghost" size="sm"><UserPlus size={16}/><span>同桌好友</span></Button></DialogTrigger><DialogContent className="social-modal"><DialogHeader><DialogTitle>同桌好友</DialogTitle><DialogDescription>向同桌玩家发出申请，对方同意后就能下次再约。</DialogDescription></DialogHeader>{error&&<p className="friends-error" role="alert">{error}</p>}<section className="social-section"><h4>这桌的牌友</h4>{peers.length?peers.map(p=>{const friend=data.friends.some(f=>f.id===p.id),outgoing=data.outgoing.some(f=>f.id===p.id),incoming=data.incoming.some(f=>f.id===p.id);return <div className="friend-row" key={p.id}><Person person={p}/><Button variant="outline" size="sm" disabled={busy||!ready||friend||outgoing||incoming||game.phase==='closed'} aria-label={`添加 ${p.name} 为好友`} onClick={()=>void add(p)}>{friend?<><Check size={14}/>已是好友</>:outgoing?'申请已发送':incoming?'待你同意':<><UserPlus size={14}/>加好友</>}</Button></div>}):<p className="friends-empty">同桌的真实玩家会出现在这里，人机不加入好友列表。</p>}</section>{problem&&<p className="friends-hint">{problem}</p>}<FriendsPanel all roomCode={code} inviteDisabled={!!problem} onJoined={()=>setOpen(false)}/></DialogContent></Dialog>;
}
