"use client";
import {useEffect,useState,type ReactNode} from 'react';
import {Share2,Check,ChevronLeft,ChevronRight,Trophy,LockKeyhole,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from '@/components/ui/accordion';
import {api} from '@/lib/client';
import {chips,resultName,type PublicRound,type Report} from '@/lib/mahjong/report';
import {typeName} from '@/lib/mahjong/solver';
import {ReportDownload} from '@/components/mahjong-report-download';
import {MahjongTile} from '@/components/mahjong-tile';
import {PlanTiles} from '@/components/mahjong-win-picker';

import {ScoreChart} from '@/components/score-report';
import {mahjongScores} from '@/lib/reports/score';

export function RoundDetails({round:r}:{round:PublicRound}){const hits=r.awards.filter(a=>a.hit).length;return <div className="ham-round-detail">{r.groups.length>0&&<><div className="ham-detail-label">{r.family==='fourWild'?'四赖直胡 · 已确认的牌张身份，不要求成型':'已确认的胡牌方案'}</div><PlanTiles groups={r.groups}/><div className="ham-fans">{r.fans.map(f=><span key={f.id}>{f.name} ×{f.multiplier}</span>)}<b>合计 ×{chips(r.multiplier)}</b></div></>}{r.awards.length>0&&<><div className="ham-awards">{r.awards.map((a,i)=><div className={a.hit?'is-hit':''} key={i}><MahjongTile tile={a.tile}/><span>{(a.tile/4|0)!==a.type?'代 '+typeName(a.type):typeName(a.type)}</span><b>{a.hit?'命中 +1':'未命中'}</b></div>)}</div><p className="ham-equation">{chips(r.base)} ×（1 + {hits}）× {chips(r.multiplier)} = <strong>{chips((BigInt(r.base)*BigInt(1+hits)*BigInt(r.multiplier)).toString())}</strong><span>每位付款者应付筹码 · {r.type==='self'?'三家各付':'仅'+r.source+'付款'}</span></p></>}{!r.awards.length&&r.winner&&<p className="ham-equation">每位付款者付 {chips(r.base)} 筹码<span>{r.type==='self'?'自摸，三家各付':'仅'+r.source+'付款'}</span></p>}{r.automatic&&<p className="muted">选择时间结束，已采用最高倍数方案；并列按固定顺序。</p>}<div className="ham-ledger">{r.entries.map((e,i)=><p key={i}><span>{e.kind==='win'?'胡牌':e.kind==='refund'?'退款':'杠分'}</span>{e.description}</p>)}</div>{r.type==='draw'&&<p className="muted">本局流局，已成功的杠分保留。</p>}{r.type==='aborted'&&<p className="muted">本局中止，本局杠分已撤销。</p>}</div>}
export function ReportContent({report:r,onPage}:{report:Report;onPage?:(page:number)=>void}){return <article className="ham-report"><header className="ham-report-header"><div><span className="ham-report-eyebrow">娱 乐 中 心{r.practice?' · 人机对局':''}</span><h2>{r.scope==='table'?'这一桌的战报':'第 '+r.rounds[0]?.number+' 局战报'}</h2><p>{r.title}</p></div><span className="ham-report-seal"><Trophy size={27}/>{r.ruleName}</span></header><div className="ham-report-meta"><span>基础 {chips(r.baseChips)} 筹码</span><span>{new Date(r.ended).toLocaleString('zh-CN',{hour12:false})}</span></div><Table className="ham-report-table"><TableHeader><TableRow><TableHead>玩家</TableHead><TableHead>{r.scope==='table'?'初始':'局前'}</TableHead><TableHead>净输赢</TableHead><TableHead>结余筹码</TableHead></TableRow></TableHeader><TableBody>{r.players.map((p,i)=><TableRow key={i}><TableCell><b>{p.name}</b>{p.bot&&<small className="bot-label">机器人</small>}</TableCell><TableCell>{chips(p.initial)}</TableCell><TableCell className={BigInt(p.delta)>=0n?'positive':'negative'}><strong>{chips(p.delta,true)}</strong></TableCell><TableCell>{chips(p.balance)}</TableCell></TableRow>)}</TableBody></Table><div className="ham-report-stats"><span><b>{r.stats.completed}</b> 完成局数</span><span><b>{r.stats.draws}</b> 流局</span><span><b>{r.stats.aborted}</b> 中止</span></div><ScoreChart report={r.scores??mahjongScores(r.players,r.rounds,r.title)}/>{r.scope==='round'&&r.rounds[0]?<><h3 className="ham-round-title">{resultName(r.rounds[0])}</h3><RoundDetails round={r.rounds[0]}/></>:<><h3 className="ham-round-title">逐局明细</h3><Accordion type="single" collapsible>{r.rounds.map(round=><AccordionItem value={String(round.number)} key={round.number}><AccordionTrigger><span>第 {round.number} 局 · {resultName(round)}</span><span className="ham-round-multi">{round.winner?'×'+chips(round.multiplier):'—'}</span></AccordionTrigger><AccordionContent><div className="ham-round-mini-scores">{round.players.map((p,i)=><span key={i}>{p.name}<b className={BigInt(p.delta)>=0n?'positive':'negative'}>{chips(p.delta,true)}</b></span>)}</div><RoundDetails round={round}/></AccordionContent></AccordionItem>)}</Accordion>{r.totalRounds>r.pageSize&&<div className="ham-report-pages"><Button size="sm" variant="outline" disabled={!r.page} onClick={()=>onPage?.(r.page-1)}><ChevronLeft size={15}/>上一页</Button><span>{r.page+1} / {Math.ceil(r.totalRounds/r.pageSize)}</span><Button size="sm" variant="outline" disabled={(r.page+1)*r.pageSize>=r.totalRounds} onClick={()=>onPage?.(r.page+1)}>下一页<ChevronRight size={15}/></Button></div>}</>}<footer><LockKeyhole size={14}/>只展示昵称、结算与胡牌牌型</footer></article>}
type Shared={id:string;scope:string;round_id:string|null;created:number;revoked:number};
function PrivateReport({code,round}:{code:string;round?:string}){
 const [r,setR]=useState<Report|null>(null),[page,setPage]=useState(0),[shares,setShares]=useState<Shared[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[url,setUrl]=useState(''),[copied,setCopied]=useState(false);
 const refreshShares=()=>api('/api/mahjong/shares?room='+code).then(d=>setShares(d.shares.filter((s:Shared)=>s.round_id===(round??null))));
 useEffect(()=>{let active=true;api(`/api/mahjong/reports?room=${code}${round?'&round='+round:''}&page=${page}`).then(d=>{if(active)setR(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[code,round,page]);
 useEffect(()=>{refreshShares().catch(e=>setError(e.message));},[code,round]);
 async function share(){setBusy(true);setError('');try{const d=await api('/api/mahjong/shares',{action:'create',code,round}),link=location.origin+d.path;setUrl(link);await refreshShares();try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setCopied(false)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <>{error&&<p className="form-error" role="alert">{error}</p>}{r?<><div className="ham-report-actions"><ReportDownload report={r} shareUrl={url}/><Button disabled={busy} onClick={share}>{copied?<Check size={17}/>:<Share2 size={17}/>}生成公开分享链接</Button></div><p className="ham-share-note">只有点击生成后才会公开这份战报，拿到链接的人无需登录即可查看。</p>{url&&<div className="ham-share-link"><a href={url} target="_blank" rel="noreferrer">{url}</a><Button size="sm" variant="ghost" onClick={()=>navigator.clipboard.writeText(url).then(()=>setCopied(true)).catch(()=>setError('请长按上方链接复制'))}>{copied?'已复制':'复制'}</Button></div>}<ReportContent report={r} onPage={setPage}/>{shares.some(s=>!s.revoked)&&<div className="ham-share-list"><h4>我生成的分享</h4>{shares.filter(s=>!s.revoked).map(s=><div key={s.id}><a href={'/share/'+s.id} target="_blank" rel="noreferrer">{new Date(s.created).toLocaleString('zh-CN')}</a><Button size="sm" variant="ghost" onClick={async()=>{try{await api('/api/mahjong/shares',{action:'revoke',id:s.id});if(url.endsWith(s.id))setUrl('');await refreshShares();}catch(e){setError((e as Error).message)}}}><X size={14}/>撤销</Button></div>)}</div>}</>:<p className="muted">正在读取战报…</p>}</>;
}
export function ReportDialog({code,round,children}:{code:string;round?:string;children?:ReactNode}){const [open,setOpen]=useState(false);return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{children??<Button variant="outline"><Trophy size={16}/>{round?'本局战报':'整桌战报'}</Button>}</DialogTrigger><DialogContent className="ham-report-modal"><DialogHeader><DialogTitle>{round?'本局战报':'整桌战报'}</DialogTitle><DialogDescription>查看收支、保存图片，或主动分享给朋友。</DialogDescription></DialogHeader>{open&&<PrivateReport code={code} round={round}/>}</DialogContent></Dialog>}
