"use client";
import {memo,useState} from 'react';
import {Check,Coins,Info,RefreshCw,ShoppingBag,Sparkles} from 'lucide-react';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
import {DeadlineClock,DeadlineButton} from './deadline-clock';
import type {RoomTiming} from '@/lib/sync/clock';
import {equipmentAvailable,type V3Game,type V3CatalogEntry,type V3Equipment} from '@/lib/game/landlord-v3';
import {shopOfferState} from '@/lib/game/shop-presentation';
const levels=['I','II','III','IV'];
export const SkillShop=memo(function SkillShop({game,seat,busy,timing,onAction}:{game:V3Game;seat:number;busy:boolean;timing:RoomTiming;onAction:(action:string,extra?:any)=>void}){
 const [detail,setDetail]=useState<V3CatalogEntry|null>(null),[selling,setSelling]=useState<V3Equipment|null>(null);
 const offers=game.shops[seat]?.offers??[],mine=game.equipment[seat]??[],catalog=game.rules.equipmentCatalog,entry=(id:string)=>catalog.find(e=>e.id===id);
 const completed=game.seats[seat]?.last==='商店完成',locked=busy||completed,used=(key:string)=>game.equipmentUsed.includes(`${seat}:${key}`);
 const open=offers.filter(o=>!o.bought),canClear=mine.some(e=>e.id==='clearance')&&!used('clearance')&&!(game.tableUsed??[]).includes('clearance'),canConnect=mine.some(e=>e.id==='connections')&&!(game.tableUsed??[]).includes(`connections:${seat}`)&&!used('clearance')&&BigInt(game.coins[seat])>=6n;
 return <><section className="v3-shop skill-shop" aria-label="技能模式商店">
  <header className="skill-shop-top"><div className="skill-shop-title"><ShoppingBag size={24}/><div><h3>装备小铺</h3><p><Coins size={14}/><b>{game.coins[seat]}</b> 金币 <span>装备 {mine.length} / 8</span></p></div></div><div className="skill-shop-controls"><DeadlineClock deadline={game.deadline} timing={timing} label="商店剩余时间"/><DeadlineButton timing={timing} deadline={game.deadline} disabled={locked} onClick={()=>onAction('shop_done')}><Check size={16}/>{completed?'已完成，等待牌友':'完成购买'}</DeadlineButton></div></header>
  <div className="skill-shop-caption"><span>先选装备，再去叫地主 · {game.seats.filter(s=>s.last==='商店完成').length} / 3 已完成</span><Button variant="ghost" size="sm" disabled={locked||used('refresh')||!mine.some(e=>e.id==='extra-refresh')} onClick={()=>onAction('shop_refresh')}><RefreshCw size={14}/>额外刷新</Button></div>
  <div className="v3-equipment-grid">{[1,2,3,4].map(level=><section className={`v3-equipment-column tier-${level}`} key={level}><h4><span className="v3-equipment-tier">{levels[level-1]}</span>{level} 级装备</h4><div>{offers.filter(o=>o.level===level).map(offer=>{const item=entry(offer.id);if(!item)return null;const state=shopOfferState(game,seat,offer);return <article key={offer.offerId} className={`skill-offer${offer.bought?' is-bought':''}`}><div className="skill-offer-symbol" aria-hidden="true"><Sparkles size={22}/><b>{item.name.slice(0,1)}</b></div><button className="skill-offer-info" type="button" onClick={()=>setDetail(item)} aria-label={`查看 ${item.name} 说明`}><strong>{item.name}</strong><Info size={13}/></button><p>{item.effect}</p><div className="skill-offer-price"><Coins size={14}/>{state.price}<small>{state.upgrade?'半价升级':'金币'}</small></div><DeadlineButton deadline={game.deadline} timing={timing} disabled={locked||!!state.reason} onClick={()=>onAction('shop_buy',{offerId:offer.offerId})} aria-label={`购买 ${item.name}，${state.price} 金币`}>{state.reason??'购买'}</DeadlineButton></article>})}</div></section>)}</div>
  <section className="skill-inventory"><h4>我的装备 <small>跨局保留 · 点击名称查看说明</small></h4>{mine.length?<div className="skill-inventory-grid">{mine.map(item=><article key={item.instanceId}><button type="button" onClick={()=>{const e=entry(item.id);if(e)setDetail(e)}}>{entry(item.id)?.name??item.id}<small>{levels[item.level-1]}</small></button><Button variant="ghost" size="sm" disabled={locked||item.nonSellable} onClick={()=>setSelling(item)}>{item.nonSellable?'不可出售':`出售 · +${item.level===1?'0':String(BigInt(item.price)/2n)}`}</Button></article>)}</div>:<p>装备袋空空的，选一件喜欢的吧。</p>}</section>
  {canClear&&<section className="skill-extra"><h4>清仓 · 免费选一件</h4>{open.map(offer=><DeadlineButton key={offer.offerId} timing={timing} deadline={game.deadline} variant="outline" disabled={locked} onClick={()=>onAction('shop_clearance',{offerId:offer.offerId})}>{entry(offer.id)?.name}</DeadlineButton>)}</section>}
  {canConnect&&<section className="skill-extra"><h4>人脉 · 6 金币指定四级装备</h4>{catalog.filter(e=>e.level===4).map(item=><DeadlineButton key={item.id} timing={timing} deadline={game.deadline} variant="outline" disabled={locked} onClick={()=>onAction('shop_connections',{equipmentId:item.id})}>{item.name}</DeadlineButton>)}</section>}
  {game.developerMode&&<details className="skill-dev"><summary>开发者装备测试</summary><div className="v3-dev-equipment">{catalog.filter(e=>equipmentAvailable(e.id)).map(item=><Button key={item.id} variant="outline" size="sm" disabled={busy||mine.some(e=>e.id===item.id)} onClick={()=>onAction('dev_equipment',{equipmentId:item.id})}>授予 {item.name}</Button>)}</div></details>}
 </section><Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}>{detail&&<DialogContent className="skill-equipment-modal"><DialogHeader><DialogTitle>{detail.name}</DialogTitle><DialogDescription>{detail.effect}</DialogDescription></DialogHeader><p>{detail.level} 级 · 标价 {detail.price} 金币</p><DeadlineClock deadline={game.deadline} timing={timing} label="商店剩余时间"/><Button onClick={()=>setDetail(null)}>返回装备小铺</Button></DialogContent>}</Dialog>
 <AlertDialog open={!!selling} onOpenChange={open=>{if(!open)setSelling(null)}}><AlertDialogContent className="skill-equipment-modal"><AlertDialogHeader><AlertDialogTitle>出售 {selling&&entry(selling.id)?.name}？</AlertDialogTitle><AlertDialogDescription>返还 {selling?.level===1?'0':selling?String(BigInt(selling.price)/2n):'0'} 金币，装备将从本桌背包移除。</AlertDialogDescription></AlertDialogHeader><DeadlineClock deadline={game.deadline} timing={timing} label="商店剩余时间"/><AlertDialogFooter><AlertDialogCancel>留在背包</AlertDialogCancel><AlertDialogAction disabled={locked||game.phase!=='shopping'} onClick={()=>{if(selling)onAction('shop_sell',{instanceId:selling.instanceId});setSelling(null)}}>确认出售</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
});
