import { env } from 'cloudflare:workers';
import {scryptSync,timingSafeEqual,randomBytes,createHash} from 'node:crypto';
export type User={id:string;username:string;display:string;password:string;role:string;banned:number;score:number};
export class AppError extends Error{constructor(message:string,public status=400){super(message)}}
export function db(){const d=(env as unknown as {DB:D1Database}).DB;if(!d)throw new AppError('服务暂不可用，请稍后重试',503);return d;}
export const vars=()=>env as unknown as Record<string,string>;
export const digest=(v:string)=>createHash('sha256').update(v).digest('hex');
export function passwordHash(password:string,salt=randomBytes(16).toString('hex')){return `scrypt:16384:8:5:${salt}:${scryptSync(password,salt,32,{N:16384,r:8,p:5,maxmem:24*1024*1024}).toString('hex')}`;}
export function passwordValid(password:string,stored:string){const parts=stored.split(':');if(parts.length!==6)return false;const actual=Buffer.from(passwordHash(password,parts[4]).split(':')[5],'hex');const wanted=Buffer.from(parts[5],'hex');return actual.length===wanted.length&&timingSafeEqual(actual,wanted);}
export function publicUser(u:User){return{id:u.id,username:u.username,name:u.display,role:u.role,score:u.score};}
export async function user(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)sanren_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;const u=await db().prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.hash=? AND s.expires>?').bind(digest(token),Date.now()).first<User>();if(u?.banned)throw new AppError('账号已被停用，请联系管理员',403);return u;}
export async function requireUser(req:Request,admin=false){const u=await user(req);if(!u)throw new AppError('请先登录',401);if(admin&&u.role!=='admin')throw new AppError('仅管理员可以执行此操作',403);return u;}
export function json(data:unknown,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin',...headers}});}
export async function safe(fn:()=>Promise<Response>){try{return await fn()}catch(e){if(e instanceof AppError)return json({error:e.message},e.status);console.error('Request failed',e instanceof Error?e.message:'unknown');return json({error:'暂时无法完成，请重试'},503);}}
export async function body(req:Request){if(req.headers.get('sec-fetch-site')==='cross-site')throw new AppError('请求来源无效',403);const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new AppError('请求来源无效',403);if(!req.headers.get('content-type')?.includes('application/json'))throw new AppError('请求格式无效');const text=await req.text();if(text.length>16384)throw new AppError('请求过大',413);try{return JSON.parse(text)}catch{throw new AppError('请求格式无效')}}
export async function limit(key:string,max:number,minutes=15){const now=Date.now();const row=await db().prepare('INSERT INTO limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END, expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END RETURNING count').bind(key,now+minutes*60000,now,now).first<{count:number}>();if(!row||row.count>max)throw new AppError('操作过于频繁，请稍后再试',429);}
export async function config(){const rows=await db().prepare('SELECT key,value FROM settings WHERE key IN (?,?,?)').bind('seconds','announcement','maintenance').all<{key:string;value:string}>();const o=Object.fromEntries(rows.results.map(x=>[x.key,x.value]));return{seconds:Number(o.seconds||30),announcement:!o.announcement||['欢迎来三人局。建个房间，把房间号发给朋友就能入座。','欢迎来娱乐中心。建个房间，把房间号发给朋友就能入座。'].includes(o.announcement)?'':o.announcement,maintenance:o.maintenance==='true'};}
export function cookie(token:string,req:Request,age=604800){return `sanren_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`;}
