import {sqliteTable,text,integer,blob,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),username:text('username').notNull(),display:text('display').notNull(),password:text('password').notNull(),role:text('role').notNull().default('player'),banned:integer('banned').notNull().default(0),score:integer('score').notNull().default(0),created:integer('created').notNull()},t=>[uniqueIndex('idx_users_username').on(t.username)]);
export const sessions=sqliteTable('sessions',{hash:text('hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()},t=>[index('idx_sessions_expires').on(t.expires)]);
export const rooms=sqliteTable('rooms',{code:text('code').primaryKey(),title:text('title').notNull(),state:text('state').notNull(),phase:text('phase').notNull(),revision:integer('revision').notNull().default(0),op:text('op').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('idx_rooms_phase_updated').on(t.phase,t.updated)]);
export const members=sqliteTable('members',{userId:text('user_id').primaryKey().references(()=>users.id),roomCode:text('room_code').notNull().references(()=>rooms.code)},t=>[index('idx_members_room').on(t.roomCode)]);
export const roomMessages=sqliteTable('room_messages',{id:integer('id').primaryKey({autoIncrement:true}),roomCode:text('room_code').notNull().references(()=>rooms.code),authorId:text('author_id').notNull().references(()=>users.id),clientId:text('client_id').notNull(),display:text('display').notNull(),text:text('text').notNull(),kind:text('kind').notNull().default('text'),emoteId:text('emote_id'),created:integer('created').notNull()},t=>[index('idx_room_messages_author_kind_created').on(t.authorId,t.kind,t.created),index('idx_room_messages_room_id').on(t.roomCode,t.id),uniqueIndex('idx_room_messages_retry').on(t.roomCode,t.authorId,t.clientId)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const records=sqliteTable('records',{id:text('id').primaryKey(),roomCode:text('room_code').notNull(),result:text('result').notNull(),created:integer('created').notNull()},t=>[index('idx_records_created').on(t.created),index('idx_records_room_created').on(t.roomCode,t.created)]);
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),created:integer('created').notNull()});
export const chipEntries=sqliteTable('chip_entries',{id:text('id').primaryKey(),roomCode:text('room_code').notNull(),roundId:text('round_id').notNull(),kind:text('kind').notNull(),entry:text('entry').notNull(),created:integer('created').notNull()},t=>[index('idx_chip_room_round').on(t.roomCode,t.roundId)]);
export const mahjongShares=sqliteTable('mahjong_shares',{id:text('id').primaryKey(),creator:text('creator').notNull().references(()=>users.id),roomCode:text('room_code').notNull(),scope:text('scope').notNull(),roundId:text('round_id'),roundLimit:integer('round_limit').notNull(),snapshot:text('snapshot').notNull(),created:integer('created').notNull(),revoked:integer('revoked').notNull().default(0)},t=>[index('idx_mj_shares_creator').on(t.creator,t.created)]);

export const friendships=sqliteTable('friendships',{userLow:text('user_low').notNull().references(()=>users.id),userHigh:text('user_high').notNull().references(()=>users.id),requestedBy:text('requested_by').notNull().references(()=>users.id),created:integer('created').notNull(),accepted:integer('accepted')},t=>[primaryKey({columns:[t.userLow,t.userHigh]}),index('idx_friendships_high').on(t.userHigh)]);
export const userPresence=sqliteTable('user_presence',{sessionHash:text('session_hash').primaryKey().references(()=>sessions.hash,{onDelete:'cascade'}),seen:integer('seen').notNull()});
export const roomInvites=sqliteTable('room_invites',{id:text('id').primaryKey(),roomCode:text('room_code').notNull().references(()=>rooms.code),sender:text('sender').notNull().references(()=>users.id),recipient:text('recipient').notNull().references(()=>users.id),created:integer('created').notNull(),expires:integer('expires').notNull(),dismissed:integer('dismissed').notNull().default(0)},t=>[uniqueIndex('idx_room_invites_room_recipient').on(t.roomCode,t.recipient),index('idx_room_invites_recipient').on(t.recipient,t.dismissed,t.expires)]);

export const userAvatars=sqliteTable('user_avatars',{userId:text('user_id').primaryKey().references(()=>users.id),version:integer('version').notNull(),image:blob('image',{mode:'buffer'}),mime:text('mime').notNull(),updated:integer('updated').notNull()});
